<a href="https://colab.research.google.com/github/AqsaAamena/Basic-Python-Projects/blob/main/Special_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()
for fn in uploaded.keys():
  print(f"user uploaded file {fn}")

Saving Employees.csv to Employees.csv
user uploaded file Employees.csv

In [ ]:
filepath='/content/Employees.csv'
#Load the CSV dataset into a DataFrame.
df=pd.read_csv(filepath)
df

,No,First Name,Last Name,Gender,Start Date,Years,Department,Country,Center,Monthly Salary,Annual Salary,Job Rate,Sick Leaves,Unpaid Leaves,Overtime Hours
0,1,Ghadir,Hmshw,Male,4/4/2018,8,Quality Control,Egypt,West,1560,18720,3.0,1,0,183
1,2,Omar,Hishan,Male,5/21/2020,6,Quality Control,Saudi Arabia,West,3247,38964,1.0,0,5,198
2,3,Ailya,Sharaf,Female,9/28/2017,8,Major Mfg Projects,Saudi Arabia,West,2506,30072,2.0,0,3,192
3,4,Lwiy,Qbany,Male,8/14/2018,7,Manufacturing,United Arab Emirates,Main,1828,21936,3.0,0,0,7
4,5,Ahmad,Bikri,Male,3/11/2020,6,Manufacturing,Egypt,Main,970,11640,5.0,0,5,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684,685,Sari,Hanna,Male,5/26/2020,6,Marketing,Lebanon,South,1452,17424,2.0,0,3,1
685,686,Eubayda,Kayd,Male,6/3/2020,6,Facilities/Engineering,Egypt,North,3237,38844,3.0,1,0,4
686,687,Khalil,Alkalu,Male,7/11/2017,8,Facilities/Engineering,Egypt,North,2819,33828,5.0,0,0,0
687,688,Muhamad,Shrbjy,Male,5/30/2018,8,Creative,Egypt,North,2069,24828,3.0,0,0,10
688,689,Abd Albasit,AlAhmar,Male,8/5/2020,5,IT,United Arab Emirates,North,2606,31272,5.0,0,0,0

In [ ]:
df.head()

,No,First Name,Last Name,Gender,Start Date,Years,Department,Country,Center,Monthly Salary,Annual Salary,Job Rate,Sick Leaves,Unpaid Leaves,Overtime Hours
0,1,Ghadir,Hmshw,Male,4/4/2018,8,Quality Control,Egypt,West,1560,18720,3.0,1,0,183
1,2,Omar,Hishan,Male,5/21/2020,6,Quality Control,Saudi Arabia,West,3247,38964,1.0,0,5,198
2,3,Ailya,Sharaf,Female,9/28/2017,8,Major Mfg Projects,Saudi Arabia,West,2506,30072,2.0,0,3,192
3,4,Lwiy,Qbany,Male,8/14/2018,7,Manufacturing,United Arab Emirates,Main,1828,21936,3.0,0,0,7
4,5,Ahmad,Bikri,Male,3/11/2020,6,Manufacturing,Egypt,Main,970,11640,5.0,0,5,121

In [ ]:
df.tail()

,No,First Name,Last Name,Gender,Start Date,Years,Department,Country,Center,Monthly Salary,Annual Salary,Job Rate,Sick Leaves,Unpaid Leaves,Overtime Hours
684,685,Sari,Hanna,Male,5/26/2020,6,Marketing,Lebanon,South,1452,17424,2.0,0,3,1
685,686,Eubayda,Kayd,Male,6/3/2020,6,Facilities/Engineering,Egypt,North,3237,38844,3.0,1,0,4
686,687,Khalil,Alkalu,Male,7/11/2017,8,Facilities/Engineering,Egypt,North,2819,33828,5.0,0,0,0
687,688,Muhamad,Shrbjy,Male,5/30/2018,8,Creative,Egypt,North,2069,24828,3.0,0,0,10
688,689,Abd Albasit,AlAhmar,Male,8/5/2020,5,IT,United Arab Emirates,North,2606,31272,5.0,0,0,0

In [ ]:
df.columns

Index(['No', 'First Name', 'Last Name', 'Gender', 'Start Date', 'Years',
       'Department', 'Country', 'Center', 'Monthly Salary', 'Annual Salary',
       'Job Rate', 'Sick Leaves', 'Unpaid Leaves', 'Overtime Hours'],
      dtype='object')

In [ ]:
df.shape

(689, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   No              689 non-null    int64
 1   First Name      689 non-null    object
 2   Last Name       689 non-null    object
 3   Gender          689 non-null    object
 4   Start Date      689 non-null    object
 5   Years           689 non-null    int64
 6   Department      689 non-null    object
 7   Country         689 non-null    object
 8   Center          689 non-null    object
 9   Monthly Salary  689 non-null    int64
 10  Annual Salary   689 non-null    int64
 11  Job Rate        689 non-null    float64
 12  Sick Leaves     689 non-null    int64
 13  Unpaid Leaves   689 non-null    int64
 14  Overtime Hours  689 non-null    int64
dtypes: float64(1), int64(7), object(7)
memory usage: 80.9+ KB

In [ ]:
df.describe()

,No,Years,Monthly Salary,Annual Salary,Job Rate,Sick Leaves,Unpaid Leaves,Overtime Hours
count,689.000000,689.000000,689.000000,689.000000,689.000000,689.000000,689.000000,689.000000
mean,345.000000,6.953556,2068.201742,24818.420900,3.586357,1.609579,0.759071,13.702467
std,199.041453,1.296526,763.289240,9159.470878,1.350125,2.196051,1.647764,25.692049
min,1.000000,5.000000,703.000000,8436.000000,1.000000,0.000000,0.000000,0.000000
25%,173.000000,6.000000,1436.000000,17232.000000,3.000000,0.000000,0.000000,3.000000
50%,345.000000,7.000000,2077.000000,24924.000000,3.000000,0.000000,0.000000,7.000000
75%,517.000000,8.000000,2682.000000,32184.000000,5.000000,3.000000,0.000000,10.000000
max,689.000000,10.000000,3450.000000,41400.000000,5.000000,6.000000,6.000000,198.000000

In [ ]:
df.dtypes

No                  int64
First Name         object
Last Name          object
Gender             object
Start Date         object
Years               int64
Department         object
Country            object
Center             object
Monthly Salary      int64
Annual Salary       int64
Job Rate          float64
Sick Leaves         int64
Unpaid Leaves       int64
Overtime Hours      int64
dtype: object

In [ ]:
df.isnull().sum()

No                0
First Name        0
Last Name         0
Gender            0
Start Date        0
Years             0
Department        0
Country           0
Center            0
Monthly Salary    0
Annual Salary     0
Job Rate          0
Sick Leaves       0
Unpaid Leaves     0
Overtime Hours    0
dtype: int64

In [ ]:
df.nunique()

No                689
First Name        299
Last Name         579
Gender              2
Start Date        539
Years               6
Department         20
Country             5
Center              5
Monthly Salary    613
Annual Salary     613
Job Rate            5
Sick Leaves         7
Unpaid Leaves       7
Overtime Hours     74
dtype: int64

In [26]:
df.sample(3)

,No,First Name,Last Name,Gender,Start Date,Years,Department,Country,Center,Monthly Salary,Annual Salary,Job Rate,Sick Leaves,Unpaid Leaves,Overtime Hours
363,364,Ahmad,Iidlibi,Male,6/6/2019,7,Marketing,Saudi Arabia,East,1255,15060,3.0,6,0,0
431,432,Muhamad,Tamur,Male,7/6/2019,7,Manufacturing,Egypt,Main,2977,35724,4.5,0,0,8
136,137,Habib,Klizli,Male,2/9/2020,6,Quality Assurance,Egypt,North,2908,34896,3.0,0,0,12

In [ ]:
df.value_counts()

No   First Name   Last Name        Gender  Start Date  Years  Department                   Country               Center  Monthly Salary  Annual Salary  Job Rate  Sick Leaves  Unpaid Leaves  Overtime Hours
689  Abd Albasit  AlAhmar          Male    8/5/2020    5      IT                           United Arab Emirates  North   2606            31272          5.0       0            0              0                 1
673  Muhamad      Sharif Aldaghly  Male    1/4/2018    8      IT                           Egypt                 West    3257            39084          3.0       0            0              6                 1
672  Jihan        Nadir            Female  4/18/2019   7      Facilities/Engineering       United Arab Emirates  North   1045            12540          5.0       6            0              4                 1
671  Ayly         Bahriin          Male    9/14/2017   8      Professional Training Group  Saudi Arabia          Main    1232            14784          5.0       3            0              10                1
670  Dania        Earmush          Female  12/1/2019   6      Product Development          United Arab Emirates  Main    2760            33120          1.0       6            6              1                 1
                                                                                                                                                                                                               ..
6    Muhamad      Zueitr           Male    2/2/2016    10     Product Development          Saudi Arabia          North   2332            27984          3.0       3            0              8                 1
5    Ahmad        Bikri            Male    3/11/2020   6      Manufacturing                Egypt                 Main    970             11640          5.0       0            5              121               1
4    Lwiy         Qbany            Male    8/14/2018   7      Manufacturing                United Arab Emirates  Main    1828            21936          3.0       0            0              7                 1
3    Ailya        Sharaf           Female  9/28/2017   8      Major Mfg Projects           Saudi Arabia          West    2506            30072          2.0       0            3              192               1
2    Omar         Hishan           Male    5/21/2020   6      Quality Control              Saudi Arabia          West    3247            38964          1.0       0            5              198               1
Name: count, Length: 689, dtype: int64